services:
  desktop:
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3001:3001"
    environment:
      MAX_RES: ${MAX_RES:-1280x720}
      SELKIES_FRAMERATE: ${SELKIES_FRAMERATE:-24}
      SELKIES_H264_CRF: ${SELKIES_H264_CRF:-30}
      SELKIES_AUDIO_ENABLED: ${SELKIES_AUDIO_ENABLED:-false|locked}
      SELKIES_MICROPHONE_ENABLED: ${SELKIES_MICROPHONE_ENABLED:-false|locked}
      SELKIES_GAMEPAD_ENABLED: ${SELKIES_GAMEPAD_ENABLED:-false|locked}
      SELKIES_FILE_TRANSFERS: ${SELKIES_FILE_TRANSFERS:-none|locked}
      SELKIES_ENABLE_SHARING: ${SELKIES_ENABLE_SHARING:-false|locked}
